# Loaded for interactive shells.

# Prepend startup functions path and remove duplicates.
typeset -Ua fpath
fpath=("$DOTFILES/zsh/functions/startup" $fpath)
autoload -Uz $DOTFILES/zsh/functions/startup/*(.:t)

verbose Loading $fg[green]zshrc$reset_color

# Load color support.
autoload -U colors && colors

# shellcheck disable=SC2034
ZPLUG_LOADFILE=$DOTFILES/zsh/zplugs

# Use extended_glob option for zplug subshells. We need to change it for zplug's use tags containing extended globs.
zstyle ':zplug:config:setopt' only_subshell extended_glob

if ! zplug-init zplug-apply-unreleased-fixes; then
  return 1
fi

zplug-install

# Need to apply fixes once more after installing because zplug installs itself.
zplug-apply-unreleased-fixes

# Source plugins and add commands to the PATH.
zplug load ${ZSH_VERBOSE/true/--verbose}

# Clean up after ourselves.
undefine-startup-functions


# vim: set ft=zsh ts=2 sw=2 et:
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
export PATH="/usr/local/opt/curl/bin:$PATH"

export PATH="$HOME/Library/Android/sdk/platform-tools:$HOME/Library/Android/sdk/tools:$HOME/Library/Android/sdk/build-tools/30.0.1:/usr/local/sbin:$PATH"
